export const restaurantData = {
  restaurants: [
    {
      id: "bread-bakery",
      name: "Bread & Bakery",
      category: "Bakery",
      deliveryEstimate: "25m",
      rating: 4.9,
      imagePath: "assets/img/restaurants/breadbakery.jpg",
      about:
        "A Bread & Brakery tem 40 anos de mercado. Fazemos os melhores doces e pães. Compre e confira.",
      hours: "Funciona de segunda à sexta, de 8h às 23h",
    },
    {
      id: "burger-house",
      name: "Burger House",
      category: "Hamburgers",
      deliveryEstimate: "100m",
      rating: 3.5,
      imagePath: "assets/img/restaurants/burgerhouse.jpeg",
      about: "40 anos se especializando em trash food.",
      hours: "Funciona todos os dias, de 10h às 22h",
    },
    {
      id: "coffee-corner",
      name: "Coffee Corner",
      category: "Coffee Shop",
      deliveryEstimate: "30-40m",
      rating: 4.8,
      imagePath: "assets/img/restaurants/coffeecorner.jpeg",
      about: "A Coffe Corner foi eleita a melhor cafeteria da cidade.",
      hours: "Funciona de segunda à sábado, de 6h às 22h",
    },
    {
      id: "green-food",
      name: "Green Food",
      category: "Saudável",
      deliveryEstimate: "75m",
      rating: 4.1,
      imagePath: "assets/img/restaurants/greenfood.jpeg",
      about:
        "Comida saudável é no Green Food. Compramos barato, vendemos caro. ;)",
      hours: "Somente em horário de almoço, das 11h às 15h",
    },
    {
      id: "ice-cream",
      name: "Ice Cream",
      category: "Ice Creams",
      deliveryEstimate: "40-65m",
      rating: 4.5,
      imagePath: "assets/img/restaurants/icecream.jpg",
      about: "A Ice Cream é uma sorveteria inovadora.",
      hours: "Funciona todos os dias, de 10h às 1h",
    },
    {
      id: "tasty-treats",
      name: "Tasty Treats",
      category: "Doces",
      deliveryEstimate: "20m",
      rating: 4.4,
      imagePath: "assets/img/restaurants/tastytreat.jpg",
      about: "A doceria com mais tradição da cidade",
      hours: "Funciona de segunda à sábado, de 8h às 23h",
    },
  ],
};
